require("mini.ai").setup()
require("mini.operators").setup()
require("mini.surround").setup()
require("mini.bracketed").setup()
require("mini.pairs").setup()
require("mini.move").setup()
require("mini.comment").setup()
