-- return {
-- 	{
-- 		"VonHeikemen/lsp-zero.nvim",
-- 		branch = "v4.x",
-- 		lazy = true,
-- 		config = false,
-- 	},
return {
	{
		"mason-org/mason.nvim",
		lazy = false,
		opts = {},
	},
}
--
-- 	-- Autocompletion
--
-- 	-- LSP
-- 	{
-- 		"neovim/nvim-lspconfig",
-- 		cmd = { "LspInfo", "LspInstall", "LspStart" },
-- 		event = { "BufReadPre", "BufNewFile" },
-- 		dependencies = {
-- 			{ "hrsh7th/cmp-nvim-lsp" },
-- 			{ "mason-org/mason.nvim" },
-- 			{ "mason-org/mason-lspconfig.nvim" },
-- 		},
-- 		init = function()
-- 			-- Reserve a space in the gutter
-- 			-- This will avoid an annoying layout shift in the screen
-- 			vim.opt.signcolumn = "yes"
-- 		end,
-- 		config = function()
-- 			local lsp_defaults = require("lspconfig").util.default_config
--
-- 			-- Add cmp_nvim_lsp capabilities settings to lspconfig
-- 			-- This should be executed before you configure any language server
-- 			lsp_defaults.capabilities =
-- 				vim.tbl_deep_extend("force", lsp_defaults.capabilities, require("cmp_nvim_lsp").default_capabilities())
--
-- 			-- LspAttach is where you enable features that only work
-- 			-- if there is a language server active in the file
-- 			vim.api.nvim_create_autocmd("LspAttach", {
-- 				desc = "LSP actions",
-- 				callback = function(event)
-- 					local opts = { buffer = event.buf }
-- 					local client = vim.lsp.get_client_by_id(event.data.client_id)
--
-- 					vim.keymap.set("n", "K", "<cmd>lua vim.lsp.buf.hover()<cr>", opts)
-- 					vim.keymap.set("n", "gd", "<cmd>lua vim.lsp.buf.definition()<cr>", opts)
-- 					vim.keymap.set("n", "gD", "<cmd>lua vim.lsp.buf.declaration()<cr>", opts)
-- 					vim.keymap.set("n", "gi", "<cmd>lua vim.lsp.buf.implementation()<cr>", opts)
-- 					vim.keymap.set("n", "go", "<cmd>lua vim.lsp.buf.type_definition()<cr>", opts)
-- 					vim.keymap.set("n", "gr", "<cmd>lua vim.lsp.buf.references()<cr>", opts)
-- 					vim.keymap.set("n", "gs", "<cmd>lua vim.lsp.buf.signature_help()<cr>", opts)
-- 					vim.keymap.set("n", "<F2>", "<cmd>lua vim.lsp.buf.rename()<cr>", opts)
-- 					vim.keymap.set({ "n", "x" }, "<F3>", "<cmd>lua vim.lsp.buf.format({async = true})<cr>", opts)
-- 					vim.keymap.set("n", "<F4>", "<cmd>lua vim.lsp.buf.code_action()<cr>", opts)
--
-- 					-- if client and client.server_capabilities.inlayHintProvider then
-- 					-- 	vim.lsp.inlay_hint.enable(true, { bufnr = opts.buffer })
-- 					-- end
--
-- 					if vim.lsp.codelens then
-- 						vim.lsp.codelens.refresh()
-- 						vim.api.nvim_create_autocmd({ "BufEnter", "CursorHold", "InsertLeave" }, {
-- 							buffer = opts.buffer,
-- 							callback = vim.lsp.codelens.refresh,
-- 						})
-- 					end
-- 				end,
-- 			})
--
-- 			require("mason-lspconfig").setup({
-- 				ensure_installed = {},
-- 				handlers = {
-- 					-- this first function is the "default handler"
-- 					-- it applies to every language server without a "custom handler"
-- 					function(server_name)
-- 						require("lspconfig")[server_name].setup({})
-- 					end,
-- 					lua_ls = function()
-- 						require("lspconfig").lua_ls.setup({
-- 							capabilities = lsp_defaults.capabilities,
-- 							settings = {
-- 								Lua = {
-- 									runtime = {
-- 										version = "LuaJIT",
-- 									},
-- 									diagnostics = {
-- 										globals = { "vim" },
-- 									},
-- 									workspace = {
-- 										library = {
-- 											vim.env.VIMRUNTIME,
-- 										},
-- 									},
-- 									hint = {
-- 										enable = true,
-- 										paramName = "All",
-- 										paramType = true,
-- 									},
-- 								},
-- 							},
-- 						})
-- 					end,
-- 					ts_ls = function()
-- 						require("lspconfig").ts_ls.setup({
-- 							capabilities = lsp_defaults.capabilities,
-- 							settings = {
--
-- 								javascript = {
-- 									inlayHints = {
-- 										includeInlayEnumMemberValueHints = true,
-- 										includeInlayFunctionLikeReturnTypeHints = true,
-- 										includeInlayFunctionParameterTypeHints = true,
-- 										includeInlayParameterNameHints = "all", -- 'none' | 'literals' | 'all';
-- 										includeInlayParameterNameHintsWhenArgumentMatchesName = true,
-- 										includeInlayPropertyDeclarationTypeHints = true,
-- 										includeInlayVariableTypeHints = false,
-- 									},
-- 								},
--
-- 								typescript = {
-- 									inlayHints = {
-- 										includeInlayEnumMemberValueHints = true,
-- 										includeInlayFunctionLikeReturnTypeHints = true,
-- 										includeInlayFunctionParameterTypeHints = true,
-- 										includeInlayParameterNameHints = "all", -- 'none' | 'literals' | 'all';
-- 										includeInlayParameterNameHintsWhenArgumentMatchesName = true,
-- 										includeInlayPropertyDeclarationTypeHints = true,
-- 										includeInlayVariableTypeHints = false,
-- 									},
-- 								},
-- 							},
-- 						})
-- 					end,
-- 					jdtls = function()
-- 						require("lspconfig").jdtls.setup({})
-- 					end,
-- 				},
-- 			})
-- 		end,
-- 	},
-- }
